version: '3.7'

services:

  # PostgreSQL:
  #   image: postgres
  #   container_name: PostgreSQL
  #   ports:
  #     - 3306:3306 # TODO: change
  #   volumes:
  #     - DB:/var/lib/mysql # TODO: change
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # back_auth:
  #   build: ./srcs/back/auth
  #   image: back_auth
  #   container_name: back_auth
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # back_chat:
  #   build: ./srcs/back/chat
  #   image: back_chat
  #   container_name: back_chat
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # back_game:
  #   build: ./srcs/back/game
  #   image: back_game
  #   container_name: back_game
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure
  
  # back_profile:
  #   build: ./srcs/back/profile
  #   image: back_profile
  #   container_name: back_profile
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # back_bootstrap:
  #   build: ./srcs/back/bootstrap
  #   image: back_bootstrap
  #   container_name: back_bootstrap
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # front_auth:
  #   build: ./srcs/front/auth
  #   image: front_auth
  #   container_name: front_auth
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # front_game:
  #   build: ./srcs/front/game
  #   image: front_game
  #   container_name: front_game
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # front_chat:
  #   build: ./srcs/front/chat
  #   image: front_chat
  #   container_name: front_chat
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  # front_profile:
  #   build: ./srcs/front/profile
  #   image: front_profile
  #   container_name: front_profile
  #   networks:
  #     - ft_transcendence
  #   restart: on-failure

  front_bootstrap:
    build: ./srcs/front/bootstrap
    image: back_bootstrap
    container_name: front_bootstrap
    networks:
      - ft_transcendence
    restart: on-failure

networks:
  ft_transcendence:
    driver: bridge

  

  
  # volumes:  to not forget

# volumes:
#   DB:
#     driver_opts:
#       type: 'none'
#       o: bind
#       device: /home/sakllam/data/mysql
