version: '3.7'


# don't forget to add a database and it's volume
services:

  my_base:
    build: ./srcs
    image: new_node_base
    container_name: new_node_base

  back:
    build: ./srcs/back
    user: "1000:1000"
    command: "sh script.sh"
    image: back
    container_name: back
    networks:
      - ft_transcendence
    restart: on-failure
    volumes:
      - vol_back:/var/www/html/

  front:
    build: ./srcs/front
    user: "1000:1000"
    command: "sh script.sh"
    image: front
    container_name: front
    networks:
      - ft_transcendence
    restart: on-failure
    volumes:
      - vol_front:/var/www/html/
    
  dataBase:
    image: postgres
    container_name: dataBase
    networks:
      - ft_transcendence
    restart: on-failure
    volumes:
      - vol_dataBase:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=evblood123
      - POSTGRES_DB=ft_transcendence

networks:
  ft_transcendence:
    driver: bridge

volumes:
  vol_back:
    driver_opts:
      o: bind
      type: 'none'
      device: /home/sakllam/Desktop/ft_transcendence/Data/back
  vol_front:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/sakllam/Desktop/ft_transcendence/Data/front
  vol_dataBase:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/sakllam/Desktop/ft_transcendence/Data/base
